# Generated by Django 3.0.9 on 2020-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Sechdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_start_date', models.DateField()),
                ('sem_end_date', models.DateField()),
                ('course_title', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('no_of_sessions', models.CharField(max_length=11)),
                ('number_of_hour_in_each_session', models.CharField(max_length=11)),
                ('total_number_of_hours', models.CharField(max_length=11)),
                ('faculty_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Sechdule',
            },
        ),
        migrations.CreateModel(
            name='Students_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_project', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('no_of_students', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Students_Projects',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('units_title', models.CharField(max_length=200)),
                ('weighatge', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='Teaching_Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('number_of_collaborators', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Teaching_Materials',
            },
        ),
    ]
