# Generated by Django 3.0.9 on 2020-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sechdule',
            old_name='sem_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='sechdule',
            old_name='sem_start_date',
            new_name='start_date',
        ),
    ]
