# Generated by Django 3.0.9 on 2020-11-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201126_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sechdule',
            new_name='se',
        ),
    ]
