# Generated by Django 3.0.9 on 2020-11-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201126_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='se',
            new_name='Sech',
        ),
    ]
